# 5 Statistical Function in PyTorch

### Subtitle Here

An short introduction about PyTorch and about the chosen functions. 
- torch.bernoulli()
- torch.poisson()
- torch.normal()
- torch.normal_()
- torch.norm()

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.bernoulli(input, *, generator=None, out=None)

It draws  binary random numbers (0 or 1) from a Bernoulli distribution.

Parameters : 

input (Tensor) – the input tensor of probability values for the Bernoulli distribution

generator (torch.Generator, optional) – a pseudorandom number generator for sampling

out (Tensor, optional) – out tensor only has values 0 or 1 and is of the same shape as input.

In [2]:
# Example 1 - # generate a  matrix 
a=torch.tensor([[0.33,0.55,0.99],[0.09,0.78,0.89],[0.29,0.19,0.39]])

In [3]:
#Draws a binary random nuber(0 or 1)
torch.bernoulli(a)

tensor([[0., 1., 1.],
        [0., 0., 1.],
        [1., 0., 0.]])

All one's in the matrix

In [4]:
# Example 2 - Here all are one's in the matrix
b = torch.ones(5, 5) # probability of drawing "1" is 1
b

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [5]:
#draw a binary number
torch.bernoulli(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

All zero's in the matrix

In [6]:
# Example 3 - 
c = torch.zeros(3, 3) # probability of drawing "1" is 0
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#draw a binary number
torch.bernoulli(c)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

These are 3 types of example of torch.bernoulli() function

Bernoulli Distribution is a random experiment that has only two outcomes (usually called a “Success” or a “Failure”).
It is best used when we have two outcomes of a given event.

## Function 2 - torch.poisson(input *, generator=None)

It returns a tensor sampled from a Poisson distribution.

Parameters:

input (Tensor) – the input tensor containing the rates of the Poisson distribution

generator (torch.Generator, optional) – a pseudorandom number generator for sampling

In [8]:
# Example 1 - working
rates = torch.rand(3, 3) * 6  # rate parameter between 0 and 6 with 3 row and 3 col 
rates

tensor([[4.5053, 0.6705, 1.3652],
        [2.0156, 0.6569, 1.2713],
        [0.1988, 2.6673, 0.5343]])

In [9]:
torch.poisson(rates)

tensor([[4., 0., 2.],
        [2., 1., 2.],
        [0., 1., 0.]])

A input tensor contain rate parameter between 0 and 6 with 3 rows and 3 columns, returns a output from a poission distribution

In [10]:
# Example 2 - working
rates = torch.rand(5, 4) * 7  # rate parameter between 0 and 7 with 5 row and 4 col 
torch.poisson(rates)

tensor([[ 3.,  3.,  5.,  4.],
        [ 0.,  4.,  0.,  2.],
        [ 1., 12.,  2.,  3.],
        [ 3.,  3.,  1.,  2.],
        [ 2.,  4.,  5.,  0.]])

A input tensor contain rate parameter between 0 and 7 with 5 rows and 4 columns, returns a output from a poission distribution

The Poisson distribution is popular for modeling the number of times an event occurs in an interval of time or space.

## Function 3 -  torch.normal(mean, std, *, generator=None, out=None) 

It returns a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

The mean is a tensor with the mean of each output element’s normal distribution

The std is a tensor with the standard deviation of each output element’s normal distribution

Parameters :

    mean (Tensor) – the tensor of per-element means

    std (Tensor) – the tensor of per-element standard deviations

    generator (torch.Generator, optional) – a pseudorandom number generator for sampling

    out (Tensor, optional) – the output tensor.

In [11]:
# Example 1 - working
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1)) 

tensor([-0.2498,  2.1719,  3.9367,  4.8688,  4.4199,  5.9211,  6.8950,  7.9340,
         9.2289, 10.0201])

It returns a tensor of random numbers drawn from separate normal distributions.

In [12]:
# Example 2 - torch.normal(mean, std=1.0, out=None) → Tensor
#Similar to the function above, but the standard-deviations are shared among all drawn elements.

#Parameters
#mean (Tensor) – the tensor of per-element means

#std (float, optional) – the standard deviation for all distributions

#out (Tensor, optional) – the output tensor
torch.normal(mean=torch.arange(3., 9.))

tensor([3.6471, 3.4960, 5.0196, 6.5287, 8.3559, 7.7088])

It returns a tensor of random numbers drawn from separate normal distributions whose  standard deviation is 1

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=0,std=1)

TypeError: normal() received an invalid combination of arguments - got (std=int, mean=int, ), but expected one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


It does not work when mean is 0 and std is 1.

The normal distribution is a probability function that describes how the values of a variable are distributed

## Function 4 - normal_(mean=0, std=1, *, generator=None)

    In-place version of torch.normal()

    Fills self tensor with elements samples from the normal distribution parameterized by mean and std.

In [26]:
# Example 1 - working
t = torch.Tensor(5, 5)
t.normal_() # Tensor.normal_(mean=0, std=1) 

tensor([[ 0.3218, -1.7837,  0.6526,  1.1876,  0.1105],
        [-1.8146, -0.8037, -0.0237, -1.4988,  0.0792],
        [ 1.1578, -1.7692,  0.2090,  0.7709,  0.1636],
        [ 1.2487,  0.0983, -0.5294,  1.0083,  0.0701],
        [-1.0426,  1.2381,  2.3188,  1.2568,  1.4765]])

It creates a standard normal distribution with mean =0 and std=1

In [28]:
# Example 2 - working
#Let's create a matrix Z (a 1d tensor) of dimension 1 × 5
torch.empty(5).normal_(mean=4,std=0.5) # random normal distribution in pytorch and mean and std are 4, 0.5 respectively

tensor([4.3953, 4.2240, 4.4564, 5.0500, 3.8047])

It create a matrix Z (a 1d tensor) of dimension 1 × 5, filled with random elements samples from the normal distribution parameterized by mean = 4 and std = 0.5.

It helps to create standard normal distribution

## Function 5 - torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)
 
It returns the matrix norm or vector norm of a given tensor.

Parameters:

    input (Tensor) – the input tensor

    p (int, float, inf, -inf, 'fro', 'nuc', optional) -the order of norm. Default: 'fro'.
    
    dim (int, 2-tuple of python:ints, 2-list of python:ints, optional) – If it is an int, vector norm will be calculated, if it is 2-tuple of ints, matrix norm will be calculated. If the value is None, matrix norm will be calculated when the input tensor only has two dimensions, vector norm will be calculated when the input tensor only has one dimension. If the input tensor has more than two dimensions, the vector norm will be applied to last dimension.

     keepdim (bool, optional) – whether the output tensors have dim retained or not. 

     out (Tensor, optional) – the output tensor. Ignored if dim = None and out = None.

     dtype (torch.dtype, optional) – the desired data type of returned tensor. 
    

In [14]:
# Example 1 - working
k = torch.tensor([[ 1, 2, 3],[-1, 1, 4]] , dtype= torch.float)
torch.norm(k, dim=0)

tensor([1.4142, 2.2361, 5.0000])

It returns vector norm of a given tensor where dim =0

In [20]:
# Example 2 - working
torch.norm(k, dim=1)

tensor([3.7417, 4.2426])

It returns vector norm of a given tensor where dim =1

In [24]:
# Example 3  
torch.norm(k, p=1, dim=1)

tensor([6., 6.])

It returns vector norm of a given tensor where dim =1 and p=1

Matrix norms are indirectly used in any applications that require matrix functions and/or matrix series.

## Conclusion

These are the 5 statistical PyTorch function that I find interesting as discussed above and link to the medium post: 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://stackoverflow.com/

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
